export const styles = {
  trigger: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    backgroundColor: 'white',
    cursor: 'pointer',
    fontSize: '14px',
    minWidth: '200px',
    textAlign: 'left' as const,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  triggerDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },
  popover: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    marginTop: '4px',
    backgroundColor: 'white',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
    zIndex: 1000,
    padding: '20px',
  },
  overlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 999,
  },
  container: {
    position: 'relative' as const,
  },
  chevron: {
    width: '16px',
    height: '16px',
    fill: 'currentColor',
  },
  calendar: {
    display: 'flex',
    gap: '32px',
  },
  month: {
    minWidth: '280px',
    display: 'flex',
    flexDirection: 'column' as const,
  },
  monthHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16px',
    padding: '0 8px',
    height: '40px',
  },
  monthTitle: {
    margin: 0,
    fontSize: '16px',
    fontWeight: '600',
    flex: 1,
    textAlign: 'center' as const,
  },
  navButton: {
    padding: '8px',
    border: 'none',
    background: 'none',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
  },
  navButtonEnabled: {
    cursor: 'pointer',
    opacity: 1,
  },
  navButtonDisabled: {
    cursor: 'not-allowed',
    opacity: 0.3,
  },
  weekdays: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    width: '100%',
    marginBottom: '8px',
  },
  weekday: {
    padding: '8px',
    textAlign: 'center' as const,
    fontSize: '12px',
    fontWeight: '600',
    color: '#6b7280',
  },
  week: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    width: '100%',
  },
  day: {
    padding: '10px',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: '14px',
    width: '40px',
    height: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  dayNormal: {
    color: '#374151',
  },
  dayOutside: {
    color: '#9ca3af',
  },
  dayToday: {
    backgroundColor: '#fef3c7',
    fontWeight: '600',
  },
  daySelected: {
    backgroundColor: '#3b82f6',
    color: 'white',
    fontWeight: '600',
  },
  dayRangeMiddle: {
    backgroundColor: '#eff6ff',
    color: '#3b82f6',
  },
  dayHover: {
    backgroundColor: '#f3f4f6',
  },
};